# Starter pipeline

trigger:
- main

pool:
  name: gokula-self-hosted

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: AzureCLI@2
  inputs:
    azureSubscription: 'gokula-connection-cli'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az deployment group create --template-file mysql.bicep --resource-group gokula-resource-group'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml